### ISSUE TITLE
General: Use XML to store Strings used in the Game

### ISSUE THREAD

**Issue by FrancoisDuchene** [OpenWeek/app-for-a-KAP#31] opened 2019-09-23 10:06 UTC
Until now, we use hardcoded strings that are directly written within the java classes.
It would be more efficient and maintainable to keep them in a separate XML file, and also would be much more easier to translate if we want one day to internationalize it.
As explain in the [stackoverflow ticket here](https://stackoverflow.com/questions/31085814/how-would-i-get-the-defined-string-in-string-xml-file-in-res-in-libgdx) and the [libgdx wiki](https://github.com/libgdx/libgdx/wiki/Internationalization-and-Localization), we just have to put the strings in the assets folder of the android folder. 
In the java classes, we should then use a special class called `I18NBundle` to handle this. This would take some patience to do but it's certainly not hard.

**Comment by timko212** [comment] 2019-10-05 14:19
Hi, I would like to work on this issue.

**Comment by FrancoisDuchene** [comment] 2019-10-06 12:21
Hello @timko212 and thank you for your interest in the project ! If you didn't do it already, i recommend you to first read the contribution guide [here](https://github.com/OpenWeek/app-for-a-KAP/blob/master/docs/CONTRIBUTING.md). I'll assume you are familiar with Java and Android development in general, but if you have a specific question about the project code, you may open an issue, we will be glad to answer them :wink: 

For this issue, there are two tasks to be done : 
- First, a class that will manage the I18Bundle and deliver the strings associated to it (watch the stackoverflow link provided in the first message). For example, a method `getString` accessible to the other classes would be great.
- Second, write every hardcoded strings into the string Properties file. Therefore in the classes, links to the bundle `getString` function will replace the old hardcoded strings with meaningful key names (e.g. for the GameOver text in **Game1**, replace with `g1_gameover`). I think it will certainly be the most boring task but it's relatively easy.  

If you are really motivated about this, i can write a Java Interface with the methods that will need to be implemented. Thanks again for your interest !

**Comment by timko212** [comment] 2019-10-27 22:46
Hello, I'm sorry that it took so long, but I will work on this issue this week. Hopefully I will solve it quickly. So, could you assign it to me?

**Comment by FrancoisDuchene** [comment] 2019-10-28 20:56
Sure, i'll let you handle this issue if you want to. Is everything clear about the task ? Feel free to ask here if you have any question 😉 
And no worries about time ! We are not pressured

**Comment by timko212** [comment] 2019-11-04 20:13
Opened pull request https://github.com/OpenWeek/app-for-a-KAP/pull/33
I think the issue is done.
Please let me know if I should change something.
Thank you.

**Closed** 2019-11-27 21:48 UTC
Labels: General, enhancement, good first issue
